apiVersion: v1
kind: ServiceAccount
metadata:
  name: congig-service-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-pods
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: congig-service-kubectl
roleRef:
  kind: Role
  name: read-pods
  apiGroup: rbac.authorization.k8s.io
