{{ if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.dnsName | replace "." "-" }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  secretName: {{ .Values.ingress.dnsName | replace "." "-" }}-cert
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.certificate.dnsName }} # We assume the common name is the same as the dnsName
  dnsNames:
    - {{ .Values.ingress.dnsName }}
{{ end }}