{{- range $key, $value := .Values.app.configMaps }} #TODO: make nicer
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$key | lower}}
data:
  {{ $value.fileName }}: {{ toYaml $value.config | indent 2 }}
---
{{- end }}
