{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{ end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.ingress.dnsName }}
    secretName: {{ .Values.ingress.dnsName | replace "." "-" }}-cert
  {{- end }}
  rules:
  - host: {{ .Values.ingress.dnsName}}
    http:
      paths:
      {{- range .Values.ingress.paths }}
        - path: {{ .path }}
          pathType: {{ .type }}
          backend:
            service:
              name: {{ $.Values.app.name }}
              port:
                number: {{ .port }}
      {{- end }}
{{ end }}