apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.service.port }}
      name: http-to-envoy
      targetPort: {{  .Values.app.authz.enabled | ternary .Values.app.authz.envoy.port .Values.app.container.port }}
