apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot-input
  labels:
    app: moonshot-input
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonshot-input
  template:
    metadata:
      labels:
        app: moonshot-input
    spec:
      containers:
      - name: moonshot-input
        image: scr.io/moonshot-samples-input:1.1
        env:
        - name: MQTT_SERVER
          value: 'mosquitto.mosquitto.svc.cluster.local'
        - name: MQTT_PORT
          value: '1883'
        volumeMounts:
        - mountPath: /etc/daytona
          name: daytona-config
        - mountPath: /etc/daytona/files
          name: daytona-files
      volumes:
      - name: daytona-config
        configMap:
          name: input-config-configmap
      - name: daytona-files
        configMap:
          name: input-tags-configmap