apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewing-mash-ml-predictions
  labels:
    app: brewing-mash-ml-predictions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brewing-mash-ml-predictions-module
  template:
    metadata:
      labels:
        app: brewing-mash-ml-predictions-module
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
        - sleep
        - "99999"